name: Deploy to ECS Fargate

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_PUBLIC_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t node-app .

      - name: Tag image
        run: |
          docker tag node-app:latest ${{ secrets.ECR_PUBLIC_REGISTRY }}/node-app:latest

      - name: Push image to ECR Public
        run: |
          docker push ${{ secrets.ECR_PUBLIC_REGISTRY }}/node-app:latest

      - name: Deploy to ECS Fargate
        run: |
          # Register a new task definition revision
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --family node-todo-app \
            --execution-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu "1024" --memory "3072" \
            --container-definitions "[{\"name\":\"node-container\",\"image\":\"${{ secrets.ECR_PUBLIC_REGISTRY }}/node-app:latest\",\"portMappings\":[{\"containerPort\":8000,\"hostPort\":8000,\"protocol\":\"tcp\"},{\"containerPort\":80,\"hostPort\":80,\"protocol\":\"tcp\"}]}]" \
            --query "taskDefinition.taskDefinitionArn" --output text)

          echo "New task definition ARN: $TASK_DEF_ARN"

          # Update ECS service to use the new task definition
          aws ecs update-service \
            --cluster node-app-cluster \
            --service node-todo-app-service \
            --task-definition $TASK_DEF_ARN
